### ISSUE TITLE
Why are there 2 "promises" by @RokuCommunity? 

### ISSUE THREAD

**Issue by EnTerr** [rokucommunity/promises#18]
The existence of 2 different projects about same feature by same maker - 
- https://github.com/rokucommunity/promises and 
- https://github.com/rokucommunity/roku-promise 

is confusing. I checked and neither of the two projects is marked as obsolete or legacy - nor recommends using the other. 

See also https://rokudevelopers.slack.com/archives/CD88K1TUJ/p1707437021946769 (which visible) 

Request: add bold text in each of them explaining what the relations are, which one newcomers should use

**Comment by TwitchBronBron** [comment]
I've added a big "error" message at the top of the legacy project. And we already had a message in the new project. So hopefully this helps make it more clear?

![image](https://github.com/rokucommunity/promises/assets/2544493/e0401899-127f-47eb-b4a6-4c83a8d8a1e2)



![image](https://github.com/rokucommunity/promises/assets/2544493/6a0b4f60-7127-43ee-8c50-594f25c8b4b1)
