### ISSUE TITLE
Unknown roSGNode 'Promise'

### ISSUE THREAD

**Issue by kosso** [rokucommunity/promises#26]
Thank you for this package. It has proved to be invaluable for my needs in the app I'm building.

I have had version `v0.1.0` working for some time, though it has always shown a Warning in the `promises_ensurePromise` function , saying `Cannot find name 'promises'`. 

I just tried the latest version `v0.5.0`, which appears to resolve the previous Warning, however it now throws an error `Unknown roSGNode 'Promise'` 

I have installed this manually, having downloaded the release zip file. 

I am using the VS Code extension `v2.50.5` and have installed `bsc-0.68.2` via npm using the extension.

Anyone have any idea how to get the latest version of `@rokucommunity/promises` working without the Unknown roSGNode error? 

Thanks.

( Also note that the `demos/simple-brightscript` example is still using `v0.1.0` )

Update: I have found that changing `"Promise"` back to `"promises_Promise"` makes the errors (and warning) go away. L6.
 Though I have no idea why. :)

**Comment by TwitchBronBron** [comment]
By default, ropm will install libraries with a prefix. This is to prevent collisions between different packages and also your own code. So if you followed the instructions and installed promises like this using `ropm`:

```
npx ropm install promises@npm:@rokucommunity/promises
```

then there will be a `promises` namespace/prefix in front of everything. This means all the namespace library functions will be `promises.*` (such as `promises.create()`, `promises.onThen()`, etc). This also means that the scenegraph node will be named `promises_Promise`. 

So this hopefully answers your question as to why you needed to change `Promise` to `promises_Promise`.

**Comment by kosso** [comment]
Thanks @TwitchBronBron. 
That makes sense now. :)

All the best.
