### ISSUE TITLE
NPM version doesn't match github version

### ISSUE THREAD

**Issue by cewert** [rokucommunity/promises#8]
[NPM version](https://www.npmjs.com/package/@rokucommunity/promises) is `0.0.1`
[Github version](https://github.com/rokucommunity/promises/releases) is `0.1.0`

**Comment by TwitchBronBron** [comment]
oops! I had to publish the first one to npm manually in order to produce the release. Then I ran another release but...looks like I forgot to uncomment the npm release flow.

![image](https://github.com/rokucommunity/promises/assets/2544493/49ce910d-2fe6-4766-b729-dad8483eac13)

**Comment by TwitchBronBron** [comment]
Should be fixed now. 
![image](https://github.com/rokucommunity/promises/assets/2544493/c7fed020-ca78-441c-9a18-797639e675f7)
